
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/


spring:
  application:
    name: curr
  profiles:
    active: dev
  cloud:
    config:
      uri: http://configserver  # Use service name as registered in Eureka
      profile: dev
      fail-fast: true
      discovery:
        enabled: true
        service-id: configserver
  config:
    import: "configserver:"

