eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    instance:
      preferIpAddress: true
      hostname: localhost

currency-api:
  key: ${CURRENCY_API_KEY:1231gredfgdas}

server:
  port: ${PORT:8002}

spring:
  application:
    name: Currency
